name: react-express

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    image: iqbalcodes6602/occ-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    image: iqbalcodes6602/occ-backend:latest
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    image: iqbalcodes6602/occ-frontend:latest
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge